log: 
  debug: true
  level: debug
  path: ./logs
  filename: server
db:
  driver: mysql
  username: root
  password: rootroot
  host: 127.0.0.1
  port: 63306
  database: go_search
  args: charset=utf8mb4&parseTime=True&loc=Local
  
  doc: 
    dir: ./data/doc
    bolt: bolt_doc.db
  
  invIndex: 
    dir: ./data/inv
    bolt: key_doc.db
  
  dict: ./data/dict.txt
  wordIds: ./data/word_ids.txt
  searchHistory: ./data/history
  last_index: 101483886

